---
title: "Project Proposal"
author: "STOR 320.002 Group 4"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

# Project Roles

- **Creator:** Dylan Fastenberg
- **Interpreter 1:** Josh Paulson 
- **Interpreter 2:** Jane Broga
- **Orator 1:** Brady Rassin
- **Orator 2:** Dylan Krakker
- **Deliverer:** Parker Wildman

# Dataset

[30000 Spotfiy Songs](https://www.kaggle.com/datasets/joebeachcapital/30000-spotify-songs)

# Initial Questions

- **Question 1:** Do energy and danceability have a correlation?
- **Question 2:** Which genre tends to have the most popular songs?
- **Question 3:** What is the distribution of danceability, energy, valence, and loudness?
- **Question 4:** What variables would be significant in a linear regression model trying to predict song popularity?
- **Question 5:** What is the relationship between number of releases per artist and average popularity of their songs over the years?
- **Question 6:** Does danceability have a relationship to how popular songs are?
- **Question 7:** Are there major differences in music between decades (eg. 2000s and 2010s)?
- **Question 8:** Does the length of a song affect its popularity? Does the genre play a role in this?
- **Question 9:** Is there any correlation between the length of a song and its impact on other variables (i.e. do longer songs have less energy or danceability vs. shorter/mid-length songs)?
- **Question 10:** Which variables of a song contribute the most to its popularity (i.e. removing what types of variables would create a completely new or arranged popularity ranking)?
- **Question 11:**
- **Question 12:**
